"""PR decision publisher — posts decisions to GitHub/Azure DevOps."""
import json
import logging
import os
import urllib.request
from typing import Dict, Optional

from .decision_engine import Decision, DecisionResult

logger = logging.getLogger(__name__)


def format_decision_comment(result: DecisionResult, analysis: Dict) -> str:
    """Format decision result as a markdown PR comment."""
    icons = {
        Decision.APPROVE: "✅",
        Decision.REJECT: "🚫",
        Decision.REQUEST_CHANGES: "🔄",
        Decision.COMMENT: "💬",
    }
    titles = {
        Decision.APPROVE: "Automated Approval",
        Decision.REJECT: "Automated Rejection",
        Decision.REQUEST_CHANGES: "Changes Requested",
        Decision.COMMENT: "AI Analysis",
    }

    icon = icons.get(result.decision, "🤖")
    title = titles.get(result.decision, "AI Review")
    s = result.findings_summary

    lines = [
        f"## {icon} {title} by Thoth AI\n",
        f"**Decision**: {result.decision.value.upper()}  ",
        f"**Confidence**: {result.confidence:.0%}  ",
        f"**Risk Score**: {result.risk_score:.0f}/100\n",
        "### 🔍 Analysis Summary",
        f"- **Critical**: {s['critical']} | **High**: {s['high']} | **Medium**: {s['medium']} | **Low**: {s['low']}",
        f"- **Reason**: {result.reason}",
    ]

    if result.blocked_by_safety:
        lines.append(f"\n⚠️ *Auto-action blocked: {result.safety_reason}*")

    # Top findings
    findings = analysis.get("findings", [])[:5]
    if findings:
        lines.append("\n### 📋 Top Findings")
        for f in findings:
            sev = f.get("severity", "?")
            lines.append(f"- **[{sev}]** {f.get('title', 'Untitled')}: {f.get('resource', 'N/A')}")

    # Recommendations
    if result.recommendations:
        lines.append("\n### 💡 Recommendations")
        for r in result.recommendations[:5]:
            lines.append(f"- {r}")

    lines.append("\n---")
    lines.append("*Generated by [ThothCTL AI Review](https://github.com/thothforge/thothctl)*")

    return "\n".join(lines)


class PRDecisionPublisher:
    """Publishes decisions to GitHub or Azure DevOps PRs."""

    def __init__(self, platform: str = "auto"):
        self.platform = self._detect_platform() if platform == "auto" else platform

    def publish(self, result: DecisionResult, analysis: Dict,
                repository: str, pr_id: str) -> Dict:
        """Publish decision to PR. Returns action result."""
        comment = format_decision_comment(result, analysis)

        if self.platform == "github":
            return self._publish_github(result, comment, repository, int(pr_id))
        elif self.platform == "azure_devops":
            return self._publish_azure_devops(result, comment, repository, int(pr_id))
        else:
            logger.warning(f"Unknown platform: {self.platform}. Comment only.")
            return {"action": "comment", "platform": self.platform, "comment": comment}

    def _publish_github(self, result: DecisionResult, comment: str,
                        repository: str, pr_number: int) -> Dict:
        """Post review to GitHub PR."""
        token = os.environ.get("GITHUB_TOKEN", "")
        if not token:
            logger.error("GITHUB_TOKEN not set")
            return {"error": "GITHUB_TOKEN not set"}

        # Map decision to GitHub review event
        event_map = {
            Decision.APPROVE: "APPROVE",
            Decision.REJECT: "REQUEST_CHANGES",
            Decision.REQUEST_CHANGES: "REQUEST_CHANGES",
            Decision.COMMENT: "COMMENT",
        }
        event = event_map.get(result.decision, "COMMENT")

        url = f"https://api.github.com/repos/{repository}/pulls/{pr_number}/reviews"
        data = json.dumps({"event": event, "body": comment}).encode()

        req = urllib.request.Request(
            url, data=data,
            headers={
                "Authorization": f"token {token}",
                "Accept": "application/vnd.github.v3+json",
            },
            method="POST",
        )

        try:
            resp = urllib.request.urlopen(req)
            resp_data = json.loads(resp.read().decode())
            logger.info(f"GitHub review posted: {event} on {repository}#{pr_number}")
            return {"action": event.lower(), "review_id": resp_data.get("id"), "url": resp_data.get("html_url")}
        except urllib.error.HTTPError as e:
            logger.error(f"GitHub API error: {e.code} - {e.read().decode()}")
            return {"error": str(e)}

    def _publish_azure_devops(self, result: DecisionResult, comment: str,
                              repository: str, pr_id: int) -> Dict:
        """Post review to Azure DevOps PR."""
        try:
            from azure.devops.connection import Connection
            from msrest.authentication import BasicAuthentication
        except ImportError:
            logger.error("azure-devops package required")
            return {"error": "azure-devops package not installed"}

        org = os.environ.get("SYSTEM_TEAMFOUNDATIONCOLLECTIONURI", "").rstrip("/").split("/")[-1]
        pat = os.environ.get("AZDO_PERSONAL_ACCESS_TOKEN", "")
        project = os.environ.get("SYSTEM_TEAMPROJECT", "")

        if not all([org, pat, project]):
            logger.error("Azure DevOps env vars not set")
            return {"error": "Missing Azure DevOps credentials"}

        # Vote: 10=approve, -10=reject, 0=no vote
        vote_map = {
            Decision.APPROVE: 10,
            Decision.REJECT: -10,
            Decision.REQUEST_CHANGES: -5,  # Wait for author
            Decision.COMMENT: 0,
        }
        vote = vote_map.get(result.decision, 0)

        try:
            creds = BasicAuthentication("", pat)
            conn = Connection(base_url=f"https://dev.azure.com/{org}", creds=creds)
            git_client = conn.clients.get_git_client()

            # Find repo ID
            repos = git_client.get_repositories(project)
            repo_id = next((r.id for r in repos if r.name == repository), None)
            if not repo_id:
                return {"error": f"Repository {repository} not found"}

            # Post comment thread
            thread = git_client.create_thread(
                {"comments": [{"content": comment, "commentType": 1}], "status": 1},
                repo_id, pr_id, project,
            )

            # Set vote if not comment-only
            if vote != 0:
                # Get current user ID (bot identity)
                identity_client = conn.clients.get_identity_client()
                me = identity_client.get_self()
                git_client.create_pull_request_reviewer(
                    {"vote": vote}, repo_id, pr_id, me.id, project,
                )

            logger.info(f"Azure DevOps review posted: vote={vote} on {repository}!{pr_id}")
            return {"action": result.decision.value, "thread_id": thread.id, "vote": vote}
        except Exception as e:
            logger.error(f"Azure DevOps API error: {e}")
            return {"error": str(e)}

    @staticmethod
    def _detect_platform() -> str:
        if os.environ.get("GITHUB_ACTIONS"):
            return "github"
        if os.environ.get("SYSTEM_TEAMFOUNDATIONCOLLECTIONURI"):
            return "azure_devops"
        return "unknown"
