"""Output formatters for AI review results."""
import json
import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)

SEVERITY_COLORS = {
    "CRITICAL": "red",
    "HIGH": "bright_red",
    "MEDIUM": "yellow",
    "LOW": "blue",
}

SEVERITY_ICONS = {
    "CRITICAL": "🔴",
    "HIGH": "🟠",
    "MEDIUM": "🟡",
    "LOW": "🔵",
}


def format_analysis_as_markdown(analysis: Dict[str, Any]) -> str:
    """Format AI analysis results as Markdown."""
    lines = ["# 🤖 AI Security Analysis Report\n"]

    summary = analysis.get("summary", {})
    lines.append("## Summary")
    lines.append(f"- **Total Findings**: {summary.get('total_findings', 0)}")
    lines.append(f"- **Critical**: {summary.get('critical', 0)}")
    lines.append(f"- **High**: {summary.get('high', 0)}")
    lines.append(f"- **Medium**: {summary.get('medium', 0)}")
    lines.append(f"- **Low**: {summary.get('low', 0)}")
    lines.append(f"- **Risk Score**: {analysis.get('risk_score', 'N/A')}/100\n")

    findings = analysis.get("findings", [])
    if findings:
        lines.append("## Findings\n")
        for i, f in enumerate(findings, 1):
            icon = SEVERITY_ICONS.get(f.get("severity", ""), "⚪")
            lines.append(f"### {icon} {i}. [{f.get('severity', 'UNKNOWN')}] {f.get('title', 'Untitled')}")
            lines.append(f"**Resource**: `{f.get('resource', 'N/A')}`\n")
            lines.append(f"{f.get('description', '')}\n")
            if f.get("remediation"):
                lines.append(f"**Remediation**: {f['remediation']}\n")
            if f.get("code_example"):
                lines.append(f"```hcl\n{f['code_example']}\n```\n")
            if f.get("compliance"):
                lines.append(f"**Compliance**: {', '.join(f['compliance'])}\n")

    recs = analysis.get("recommendations", [])
    if recs:
        lines.append("## Recommendations\n")
        for r in recs:
            lines.append(f"- {r}")

    return "\n".join(lines)


def format_analysis_as_json(analysis: Dict[str, Any]) -> str:
    """Format AI analysis results as pretty JSON."""
    return json.dumps(analysis, indent=2)


def format_pr_comment(analysis: Dict[str, Any]) -> str:
    """Format AI analysis as a PR comment."""
    summary = analysis.get("summary", {})
    risk = analysis.get("risk_score", 0)

    lines = [
        "## 🤖 ThothCTL AI Security Review\n",
        f"**Risk Score**: {risk}/100 | "
        f"**Critical**: {summary.get('critical', 0)} | "
        f"**High**: {summary.get('high', 0)} | "
        f"**Medium**: {summary.get('medium', 0)} | "
        f"**Low**: {summary.get('low', 0)}\n",
    ]

    # Only show critical and high in PR comments
    findings = [f for f in analysis.get("findings", []) if f.get("severity") in ("CRITICAL", "HIGH")]
    if findings:
        lines.append("<details><summary>🔍 Critical & High Findings</summary>\n")
        for f in findings:
            icon = SEVERITY_ICONS.get(f.get("severity", ""), "⚪")
            lines.append(f"### {icon} [{f.get('severity')}] {f.get('title', '')}")
            lines.append(f"Resource: `{f.get('resource', 'N/A')}`")
            lines.append(f"{f.get('description', '')}")
            if f.get("remediation"):
                lines.append(f"\n**Fix**: {f['remediation']}\n")
        lines.append("</details>\n")

    recs = analysis.get("recommendations", [])
    if recs:
        lines.append("### 💡 Top Recommendations")
        for r in recs[:5]:
            lines.append(f"- {r}")

    lines.append("\n---\n*Generated by ThothCTL AI Review*")
    return "\n".join(lines)
