project: test_gen
modules:
  - name: network
    repository: git@github.com/org/terraform-aws-network.git
    #version: v1.2.0
    variables:
      vpc_cidr: "10.0.0.0/16"
      environment: "production"

  - name: database
    #repository: git@github.com/org/terraform-aws-rds.git
    #version: v2.1.0
    dependencies:
      - network
    variables:
      engine: "postgres"
      instance_class: "db.t3.medium"

stacks:
  - name: production-platform
    modules:
      - network
      - database
