[test_project]
[[test_project.template_files]]
source = "test_project"
local = "file_name"
hash = "ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb"
[[test_project.template_files]]
source = "path_2"
local = "test_project/file_name"
hash = "1223ads33222d"
